### PR TITLE
move remote module poll timer creation before activation

### LINKED ISSUE #57: [Bug] remote modules do not deactivate cleanly
### Version

Release v1.4.1

### What is affected by the bug?

When deactivating a remote module on the client qudi instance, an exception is raised. After this, qudi cannot be quit normally anymore but only terminated from e.g. the console.

### When does the bug occur?

Every time when trying to deactivating a remote module on the client qudi instance.

### How do we replicate the issue?

can be replicated with e.g. data instream dummy or time series reader logic from iqo-modules

### Expected behavior

qudi should not raise an error and shut down properly when requested to.

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Software\qudi\qudi-env\lib\site-packages\qudi\core\modulemanager.py", line 601, in deactivate       
    self.__poll_timer.stop()
AttributeError: 'NoneType' object has no attribute 'stop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Software\qudi\qudi-env\lib\site-packages\qudi\core\modulemanager.py", line 208, in deactivate_module
    self._modules[module_name].deactivate()
  File "C:\Software\qudi\qudi-env\lib\site-packages\qudi\core\modulemanager.py", line 604, in deactivate       
    self._instance.module_state.sigStateChanged.disconnect(self._state_change_callback)
  File "C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\protocol.py", line 718, in sync_request
    return _async_res.value
  File "C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\async_.py", line 108, in value
    raise self._obj
_get_exception_class.<locals>.Derived: Failed to disconnect signal sigStateChanged(PyObject).

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\protocol.py", line 359, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\protocol.py", line 837, in _handle_call
    return obj(*args, **dict(kwargs))
RuntimeError: Failed to disconnect signal sigStateChanged(PyObject).
```

### Additional Comments

_No response_

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by qku**
## Description

create a poll timer (for remote modules) or connect the state changed signal (for local modules) before checking whether the module is already active

## Motivation and Context

If a module is already active on the server while the client connects, the activate method returns early and no poll timer is created. This causes the module to not deactivate cleanly later on (fixes #57 and the duplicate issue #61).

## How Has This Been Tested?

running a server and a client qudi instance on the same machine with data instream dummy from iqo-modules

## Types of changes

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change (Causes existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated the config example for any module docstrings as necessary.
- [x] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [x] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by Neverhorst** [comment]
Thank you for pointing this out and proposing a solution. 
Just so you know, this behaviour is subject to change in the coming module manager overhaul but we can fix this now if you need it urgently.

However I see a possible problem with the proposed solution:
Previously the timer for remote modules was never created (or the signal was never connected for local modules) if the activation fails at some point, i.e. raises an exception. 
Now the timer is created and started (or the signal is connected) but in case of an exception it is not terminated and destroyed (or the signal is not disconnected). This will lead to problems upon the next activation attempt.

Exception handling in the module manager needs to be done carefully and is admittedly not in a very good state, thus the coming overhaul.

**Comment by qku** [comment]
I think it would be worth trying to fix this before the module manager overhaul.

Currently it's impossible to quit the qudi client instance in a clean way if a remote module was used. #57 causes qudi to get stuck in a state where you can only force it to quit (e.g. by closing the terminal). This means that status variables cannot be saved.

**Comment by qku** [comment]
Regarding your concern with my fix @Neverhorst : I implemented cleanup in case the activation fails. Either the timer is stopped and deleted or the signal disconnected.

For testing, I configured a dummy module which fails to activate on the second activation attempt only. I can then activate it on the server and deactivate it to have it loaded. Then, I attempt to connect from the client. Activation fails and I can check whether the cleanup works as intended.

**Comment by Neverhorst** [comment]
Looks much better now, thanks.
However there is still an issue now when trying to activate an already active module. Perviously it simply returned early but now it immediately tries to connect the timer or connect the update signal even though this may have already happened. 
I understand this is what you wanted for active remote modules but this should not break when calling `activate` multiple times.

**Comment by qku** [comment]
Understood! I moved the state callback connection and added an extra condition to creating the poll timer.

**Pull request merged**
