### PR TITLE
Fit parameters as dict

### PR DESCRIPTION
**Pull request by timoML**
This PR adds an additional wrapper to the fitting module that returns fit parameters as a dict.
iqo-modules uses this dict to add the fit result to the save meta data. 

Addtionally, I changed the behavior in formatted_result() when handling fixed fit parameters.
These are now marked in the result string ("fixed") instead of silently dropped.
However, this change requires fit results that failed to input stderr=np.nan to the fit formatter, instead of lmfit's default behavior (stderr=None).

## How Has This Been Tested?
on dummy

## Types of changes
- [ ] Bug fix
- [x] New feature
- [x] Breaking change (Causes existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated the config example for any module docstrings as necessary.
- [x] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [x] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by Neverhorst** [comment]
Thanks @timoML , this looks good. 

Something I just realized since we are touching it anyway:
Do we want the result to be displayed like it is done currently, e.g. `2.67 ± 0.03 GHz`
or in the correct scientific way with brackets, e.g. `(2.67 ± 0.03) GHz`?

**Comment by timoML** [comment]
I think it's a good time to add the brackets.

**Comment by Neverhorst** [comment]
Added the brackets now. I can not find any bugs so it's fine from my side. Can you please check again @timoML with my recent changes?

**Comment by timoML** [comment]
Tested and ready to merge from my side.

**Review by Neverhorst — APPROVED** [review]

**Pull request merged**
