### PR TITLE
doc: jupyter notebook integration

### PR DESCRIPTION
**Pull request by qku**
## Description

This PR adds an article about setting up a Jupyter notebook with access to the qudi kernel.

## How Has This Been Tested?

Is there a way to test how the page will look like in the end?

## Types of changes

- [ ] Bug fix
- [X] New feature
- [ ] Breaking change (Causes existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added/updated the config example for any module docstrings as necessary.
- [ ] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by timoML** [comment]
I like it!
I started a [similar documentation](https://github.com/Ulm-IQO/qudi-iqo-modules/blob/main/docs/installation_guide.md#jupyter-notebooks-measurement-scripts) a while back in iqo-modules-repo. But qudi-core is always the better place to document basic functionality. We should merge both documents and keep yours here.

**Comment by qku** [comment]
Thanks @timoML ! I was looking there for inspiration actually. Do you think I missed something important?

**Comment by timoML** [comment]
I think I would make the start up instructions a little more verbose by mentioning
- Change to the folder where you store your jupyter notebooks.
- Note that the default address of the server is http://localhost:8888/

Also, accessing the notebook logger is not really documented somehere else, so I would add a line like:
` logger.info(f"Red laser in on: {red_laser.is_running}")`

**Comment by qku** [comment]
I like your suggestions and implemented them @timoML ! Is the log output supposed to show in jupyter somehow as well? I can only see it in the manager.

**Comment by timoML** [comment]
That's indeed intended to collect all logger ouptut in the manager (and created log files). If needed, one can probably reconfigure the logger with an additional handler.

**Review by timoML — APPROVED** [review]
Looks good. Thanks for taking your time for documentation.

**Pull request merged**
