### PR TITLE
Updating gitignore

### PR DESCRIPTION
**Pull request by prithviulm**
## Description
Updating the `.gitignore` file to be more relevant.

## Motivation and Context
The `.gitignore` file misses several files that new users may accidentally commit to the repo. Also various directories and cache files generated by testing suites, documentation generation, other IDEs (e.g. VS Code) are not currently excluded by the `.gitignore` file.

## How Has This Been Tested?
I have only tested this locally with the latest commit 8ace055a0aff38ee9e166816b12712c0337038ef from the main branch and checked that no important core files or others have been accidentally excluded.

## Types of changes
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change (Causes existing functionality to not work as expected)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated the config example for any module docstrings as necessary.
- [ ] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by prithviulm** [comment]
I haven't done the checklist because I'm not sure if it's relevant to this type of change. If I need to update the `docs/changelog.md`, let me know.

**Review by timoML — APPROVED** [review]
Thanks for taking care of this.

**Comment by timoML** [comment]
Can you create a branch for qudi-iqo-modules as well? I can merge it there without repeating another PR.

**Comment by prithviulm** [comment]
Yup I've done that here https://github.com/Ulm-IQO/qudi-iqo-modules/pull/125

**Pull request merged**
